#!/bin/sh
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/0/0ad-data/0ad-data_0.0.23.1-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/tex-gyre/fonts-texgyre_20180621-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/tex-common/tex-common_6.13_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/tex-gyre/tex-gyre_20180621-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/0/0ad-data/0ad-data-common_0.0.23.1-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/e/enet/libenet7_1.3.13+ds-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/g/gloox/libgloox17_1.0.22-0.1build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/m/miniupnpc/libminiupnpc17_2.1.20190824-0ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/n/nvidia-texture-tools/libnvtt2_2.0.8-1+dfsg-8.2build2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/o/openal-soft/libopenal-data_1.19.1-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/sndio/libsndio7.0_1.5.0-3_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/o/openal-soft/libopenal1_1.19.1-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxbase3.0-0v5_3.0.4+dfsg-15build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-gtk3-0v5_3.0.4+dfsg-15build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/0/0ad/0ad_0.0.23.1-4ubuntu3_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/3/389-ds-base/389-ds-base-libs_1.4.3.6-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/ldap-utils_2.4.49+dfsg-2ubuntu1.9_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libm/libmozilla-ldap-perl/libmozilla-ldap-perl_1.5.3-3build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/libn/libnetaddr-ip-perl/libnetaddr-ip-perl_4.079+dfsg-1build4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsocket-getaddrinfo-perl/libsocket-getaddrinfo-perl_0.22-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/c/cyrus-sasl2/libsasl2-modules-gssapi-mit_2.1.27+dfsg-2ubuntu0.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/p/python-argcomplete/python3-argcomplete_1.8.1-1.3ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/a/argparse-manpage/python3-argparse-manpage_1.2.2-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/pyasn1/python3-pyasn1_0.4.2-3build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python-pyasn1-modules/python3-pyasn1-modules_0.2.1-0.2build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python-ldap/python3-ldap_3.2.0-4ubuntu2.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python-attrs/python3-attr_19.3.0-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/m/more-itertools/python3-more-itertools_4.2.0-1build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python-zipp/python3-zipp_1.0.0-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python-importlib-metadata/python3-importlib-metadata_1.5.0-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pluggy/python3-pluggy_0.13.0-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/p/python-py/python3-py_1.8.1-1ubuntu0.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/p/python-atomicwrites/python3-atomicwrites_1.1.5-2build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/pyparsing/python3-pyparsing_2.4.6-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python-packaging/python3-packaging_20.3-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/w/wcwidth/python3-wcwidth_0.1.8+dfsg1-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/p/pytest/python3-pytest_4.6.9-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/n/nss/libnss3-tools_3.49.1-1ubuntu1.9_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/3/389-ds-base/python3-lib389_1.4.3.6-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libs/libselinux/python3-selinux_3.0-1build2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsemanage/python3-semanage_3.0-1build2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/checkpolicy/checkpolicy_3.0-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.2.1-1.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python-decorator/python3-decorator_4.4.2-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/n/networkx/python3-networkx_2.4-3ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/setools/python3-setools_4.2.2-1ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/semodule-utils/semodule-utils_3.0-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/selinux-python/python3-sepolgen_3.0-1build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/selinux-python/python3-sepolicy_3.0-1build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/3/389-ds-base/389-ds-base_1.4.3.6-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-lato/fonts-lato_2.0-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/libs/libsigsegv/libsigsegv2_2.12-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/g/gawk/gawk_5.0.1+dfsg-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdeclarative-opensource-src/libqt5qml5_5.12.8-0ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdeclarative-opensource-src/libqt5quick5_5.12.8-0ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdeclarative-opensource-src/qml-module-qtquick-window2_5.12.8-0ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdeclarative-opensource-src/qml-module-qtquick2_5.12.8-0ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtgraphicaleffects-opensource-src/qml-module-qtgraphicaleffects_5.12.8-0ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdeclarative-opensource-src/qml-module-qtquick-layouts_5.12.8-0ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtquickcontrols-opensource-src/qml-module-qtquick-controls_5.12.8-0ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtquickcontrols-opensource-src/qml-module-qtquick-privatewidgets_5.12.8-0ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtquickcontrols-opensource-src/qml-module-qtquick-dialogs_5.12.8-0ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/2/2048-qt/2048-qt_0.1.6-2build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/2/2ping/2ping_4.3-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python3-stdlib-extensions/python3-lib2to3_3.8.10-0ubuntu1~20.04_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/p/python3-defaults/2to3_3.8.2-0ubuntu2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/2/2vcard/2vcard_0.6-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/i/ibm-3270/3270-common_3.6ga4-3build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/cockpit-bridge_215-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/cockpit-ws_215-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libp/libpwquality/libpwquality-tools_1.4.2-1build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/cockpit-system_215-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/cockpit_215-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/twitter-bootstrap3/fonts-glyphicons-halflings_1.009~3.4.1+dfsg-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/twitter-bootstrap3/libjs-bootstrap_3.4.1+dfsg-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/d3/libjs-d3_3.5.17-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/c3/libjs-c3_0.4.11+dfsg-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/j/jquery/libjs-jquery_3.3.1~dfsg-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/datatables.js/libjs-jquery-datatables_1.10.20+dfsg-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/datatables-extensions/libjs-jquery-datatables-extensions_0.0+git20150910.28fd64e+dfsg-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libj/libjs-jquery-jstree/libjs-jquery-jstree_3.3.8+dfsg1-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/n/node-moment/libjs-moment_2.24.0+ds-2ubuntu0.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/3/389-ds-base/cockpit-389-ds_1.4.3.6-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/3/389-ds-base/389-ds_1.4.3.6-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap2-dev_2.4.49+dfsg-2ubuntu1.9_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/n/nspr/libnspr4-dev_4.25-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/3/389-ds-base/389-ds-base-dev_1.4.3.6-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/x/xaw3d/xaw3dg_1.5+E-18.3_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/3/3dchess/3dchess_0.8.1-20_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/ftgl/libftgl2_2.4.0-2ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/g/gsl/libgslcblas0_2.5+dfsg-6build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/g/gsl/libgsl23_2.5+dfsg-6build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/g/giflib/libgif7_5.1.9-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libh/libhdf4/libhdf4-0_4.2.14-1ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/liba/libaec/libaec0_1.0.4-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/liba/libaec/libsz2_1.0.4-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/h/hdf5/libhdf5-103_1.10.4+repack-11ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libh/libharu/libhpdf-2.3.0_2.3.0+dfsg-1build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/mathgl/libmgl-data_2.4.4-6_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/mathgl/libmgl7.5.0_2.4.4-6_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qhull/libqhull7_2015.2-4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/3/3depict/3depict_0.0.22-1.2build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/a/adcli/adcli_0.9.0-1ubuntu0.20.04.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/p/python-crypto/python3-crypto_2.6.1-13ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/tdb/python3-tdb_1.4.5-0ubuntu0.20.04.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/samba/python3-samba_4.15.13+dfsg-0ubuntu0.20.04.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/samba/samba-dsdb-modules_4.15.13+dfsg-0ubuntu0.20.04.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/python3-sss_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/libsss-idmap0_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.15.0-1ubuntu0.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/d/ding-libs/libdhash1_0.6.1-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/d/ding-libs/libbasicobjects0_0.6.1-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/d/ding-libs/libcollection4_0.6.1-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/d/ding-libs/libpath-utils1_0.6.1-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/d/ding-libs/libref-array1_0.6.1-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/d/ding-libs/libini-config5_0.6.1-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/libn/libnfsidmap/libnfsidmap2_0.25-5.1ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/libsss-certmap0_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/libsss-nss-idmap0_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-common_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-ad-common_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-krb5-common_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-ad_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/libipa-hbac0_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-ipa_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-krb5_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-ldap_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-proxy_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-dbus_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/a/adsys/adsys_0.9.2~20.04.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/a/adsys/adsys-windows_0.9.2~20.04.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/a/advancecomp/advancecomp_2.1-2.1ubuntu0.20.04.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-common_2.34-6ubuntu1.4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/libbinutils_2.34-6ubuntu1.4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/libctf-nobfd0_2.34-6ubuntu1.4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/libctf0_2.34-6ubuntu1.4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-x86-64-linux-gnu_2.34-6ubuntu1.4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils_2.34-6ubuntu1.4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/cockpit-dashboard_215-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/cockpit-networkmanager_215-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/cockpit-packagekit_215-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libb/libbytesize/libbytesize1_2.2-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/m/mdadm/mdadm_4.1-5ubuntu1.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libb/libblockdev/libblockdev-mdraid2_2.23-2ubuntu3_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/cockpit-storaged_215-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsdl1.2/libsdl1.2debian_1.2.15+dfsg2-5_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/sdl-image1.2/libsdl-image1.2_1.2.12-12_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libi/libinstpatch/libinstpatch-1.0-2_1.1.2-2build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/timgm6mb-soundfont/timgm6mb-soundfont_1.3-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fluidsynth/libfluidsynth2_2.1.1-2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libm/libmad/libmad0_0.15.1b-10ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libm/libmikmod/libmikmod3_3.3.11.1-4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/sdl-mixer1.2/libsdl-mixer1.2_1.2.12-16build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cube2/cube2_0.0.20130404+dfsg-1build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/dvisvgm/dvisvgm_2.8.1-1build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/f/finalrd/finalrd_6~ubuntu20.04.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-adf/fonts-adf-accanthis_0.20190904-1.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-adf/fonts-adf-berenis_0.20190904-1.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-adf/fonts-adf-gillius_0.20190904-1.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-adf/fonts-adf-universalis_0.20190904-1.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-cabin/fonts-cabin_1.5-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-cantarell/fonts-cantarell_0.111-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-comfortaa/fonts-comfortaa_3.001-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-dejavu/fonts-dejavu-extra_2.37-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-ebgaramond/fonts-ebgaramond_0.016-1ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-ebgaramond/fonts-ebgaramond-extra_0.016-1ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-font-awesome/fonts-font-awesome_5.0.10+really4.7.0~dfsg-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-freefont/fonts-freefont-otf_20120503-10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-gfs-artemisia/fonts-gfs-artemisia_1.1-5_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-gfs-complutum/fonts-gfs-complutum_1.1-6_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-gfs-didot/fonts-gfs-didot_1.1-6_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-gfs-neohellenic/fonts-gfs-neohellenic_1.1-6_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-gfs-olga/fonts-gfs-olga_1.1-5_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-gfs-solomos/fonts-gfs-solomos_1.1-5_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-go/fonts-go_0~20170330-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-junicode/fonts-junicode_1.002-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-linuxlibertine/fonts-linuxlibertine_5.3.0-4_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/l/lmodern/fonts-lmodern_2.004.5-6_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-lobstertwo/fonts-lobster_2.0-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-lobstertwo/fonts-lobstertwo_2.0-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-oflb-asana-math/fonts-oflb-asana-math_000.907-6_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-sil-gentium/fonts-sil-gentium_1.03-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-sil-gentium-basic/fonts-sil-gentium-basic_1.102-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-sil-gentiumplus/fonts-sil-gentiumplus_5.000-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-sil-gentiumplus-compact/fonts-sil-gentiumplus-compact_5.000-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/j/javascript-common/javascript-common_11_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/a/apache-pom/libapache-pom-java_18-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/a/audit/libauparse0_2.8.5-2ubuntu6_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/commons-parent/libcommons-parent-java_43-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libc/libcommons-logging-java/libcommons-logging-java_1.2-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/m/mecab/libmecab2_0.996-10build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/libp/libpwquality/libpam-pwquality_1.4.2-1build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/texlive-bin/libptexenc1_2019.20190605.51237-3build2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/rubygems-integration/rubygems-integration_1.16_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/ruby2.7/ruby2.7_2.7.0-5ubuntu1.8_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/ruby-defaults/ruby_2.7+1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/rake/rake_13.0.1-4_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/ruby-minitest/ruby-minitest_5.13.0-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/ruby-net-telnet/ruby-net-telnet_0.1.1-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/ruby-power-assert/ruby-power-assert_1.1.7-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/ruby-test-unit/ruby-test-unit_3.3.5-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/ruby-xmlrpc/ruby-xmlrpc_0.3.0-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/r/ruby2.7/libruby2.7_2.7.0-5ubuntu1.8_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/libs/libsocket6-perl/libsocket6-perl_0.29-1build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/tcl8.6/libtcl8.6_8.6.10+dfsg-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/teckit/libteckit0_2.5.8+ds2-5ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/texlive-bin/libtexlua53_2019.20190605.51237-3build2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/texlive-bin/libtexluajit2_2019.20190605.51237-3build2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/tk8.6/libtk8.6_8.6.10-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/libu/libusb/libusb-0.1-4_0.1.12-32_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/z/zziplib/libzzip-0-13_0.13.62-3.2ubuntu1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/l/lmodern/lmodern_2.004.5-6_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/m/m4/m4_1.4.18-4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/m/mecab/mecab-utils_0.996-10build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/mecab-jumandic/mecab-jumandic-utf8_7.0-20130310-7_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/mecab-jumandic/mecab-jumandic_7.0-20130310-7_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/mecab/mecab_0.996-10build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/n/nexuiz-data/nexuiz-textures_2.5.2-9_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libs/libselinux/selinux-utils_3.0-1build2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/p/policycoreutils/policycoreutils_3.0-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/selinux-python/policycoreutils-dev_3.0-1build1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/a/audit/python3-audit_2.8.5-2ubuntu6_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/i/ipy/python3-ipy_1.00-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/selinux-python/policycoreutils-python-utils_3.0-1build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/a/auctex/preview-latex-style_11.91-2ubuntu2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/g/gpgme1.0/python3-gpg_1.13.1-7ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/n/numpy/python3-numpy_1.17.4-5ubuntu3.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qt3d-opensource-src/qt3d5-doc-html_5.12.8+dfsg-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtbase-opensource-src/qtbase5-doc-html_5.12.8+dfsg-0ubuntu2.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtcharts-opensource-src/qtcharts5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtconnectivity-opensource-src/qtconnectivity5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdatavis3d-everywhere-src/qtdatavisualization5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdeclarative-opensource-src/qtdeclarative5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtgraphicaleffects-opensource-src/qtgraphicaleffects5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtlocation-opensource-src/qtlocation5-doc-html_5.12.8+dfsg-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtmultimedia-opensource-src/qtmultimedia5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtnetworkauth-everywhere-src/qtnetworkauth5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtquickcontrols2-opensource-src/qtquickcontrols2-5-doc-html_5.12.8+dfsg-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtquickcontrols-opensource-src/qtquickcontrols5-doc-html_5.12.8-0ubuntu2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtscript-opensource-src/qtscript5-doc-html_5.12.8+dfsg-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtscxml-everywhere-src/qtscxml5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtsensors-opensource-src/qtsensors5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtserialbus-everywhere-src/qtserialbus5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtserialport-opensource-src/qtserialport5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtsvg-opensource-src/qtsvg5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qttools-opensource-src/qttools5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtvirtualkeyboard-opensource-src/qtvirtualkeyboard5-doc-html_5.12.8+dfsg-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtwayland-opensource-src/qtwayland5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtwebchannel-opensource-src/qtwebchannel5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtwebengine-opensource-src/qtwebengine5-doc-html_5.12.8+dfsg-0ubuntu1.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtwebsockets-opensource-src/qtwebsockets5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtwebview-opensource-src/qtwebview5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtx11extras-opensource-src/qtx11extras5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtxmlpatterns-opensource-src/qtxmlpatterns5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdoc-opensource-src/qt5-doc-html_5.12.8-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/r/redeclipse-data/redeclipse-data_1.6.0-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/r/refpolicy/selinux-policy-dev_2.20190201-8_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/setools/setools_4.2.2-1ubuntu2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/supertuxkart/supertuxkart-data_1.1+ds-1build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/t1utils/t1utils_1.41-3_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/tcl8.6/tcl8.6_8.6.10+dfsg-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/tcltk-defaults/tcl_8.6.9+1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-bin/texlive-binaries_2019.20190605.51237-3build2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-base/texlive-base_2019.20200218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-extra/texlive-fonts-extra_2019.202000218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/fonts-stix/fonts-stix_1.1.1-4_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-extra/texlive-fonts-extra-links_2019.202000218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-base/texlive-fonts-recommended_2019.20200218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-base/texlive-latex-base_2019.20200218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libp/libpdfbox-java/libfontbox-java_1.8.16-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libp/libpdfbox-java/libpdfbox-java_1.8.16-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-base/texlive-latex-recommended_2019.20200218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-base/texlive-pictures_2019.20200218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-extra/texlive-latex-extra_2019.202000218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-extra/texlive-latex-extra-doc_2019.202000218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/texlive-extra/texlive-plain-generic_2019.202000218-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/thunderbird/thunderbird-dbg_102.10.0+build2-0ubuntu0.20.04.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/tipa/tipa_1.3-20_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/t/tk8.6/tk8.6_8.6.10-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/tcltk-defaults/tk_8.6.9+1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/t/ttf-aenigma/ttf-aenigma_0.0.20080510.dfsg-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/libe/libev/libev4_4.31-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/z/zeroinstall-injector/0install-core_2.15.1-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/z/zeroinstall-injector/0install_2.15.1-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/0/0xffff/0xffff_0.8-1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/a/alien-arena-data/alien-arena-data_7.66-3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/f/firefox/firefox-dbg_112.0.2+build1-0ubuntu0.20.04.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/flightgear-data/flightgear-data-base_2019.1.1+dfsg-1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/libnss-sss_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/libpam-sss_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/s/sssd/libsss-sudo_2.2.3-3ubuntu0.10_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/q/qgis/qgis-api-doc_3.10.4+dfsg-1ubuntu2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/s/sauerbraten/sauerbraten_0.0.20140302-2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/unidic-mecab/unidic-mecab_2.3.0+dfsg-6_all.deb
